### ISSUE TITLE
Please add maven dependency snippets into README.doc

### ISSUE THREAD

**Issue by pervez8ktt** [XeroAPI/Xero-Java#155]
Please add maven dependency snippets into README.doc

**Comment by SidneyAllen** [comment]
@pervez8ktt - done!

**Comment by pervez8ktt** [comment]
<repositories>
	
		<repository>
		
			<id>xero-java-mvn-repo</id>
			<url>https://raw.github.com/XeroAPI/Xero-Java/mvn-repo/</url>
			<snapshots>
				
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			
			</snapshots>
		
		</repository>
	
	</repositories>

**Comment by pervez8ktt** [comment]
please add this also

**Comment by SidneyAllen** [comment]
Hi @pervez8ktt 

I'm a bit confused by this request.  Last year we released version 2.x of the Java SDK and moved to hosting the SDK dependency on maven central instead of directly from GitHub.

You can see all the versions on Maven Central - including 3.x which supports OAuth 2.0
https://search.maven.org/search?q=g:com.github.xeroapi%20AND%20a:xero-java&core=gav
