### ISSUE TITLE
Please make ApiClient interface, not regular class, and remove photo with helicopter from library

### ISSUE THREAD

**Issue by mykolap** [XeroAPI/Xero-Java#195]
**SDK you're using (please complete the following information):**
 - Version [e.g. 3.5.1]

**Is your feature request related to a problem? Please describe.**
I would like to have ApiClient as an interface, so I don't need to have "com.github.joschi.jackson:jackson-datatype-threetenbp' in my dependencies, and don't have security vulnerabilities from that library.
Most of guys already use java8+ and don't need to have security issues only because of compatibility with java 6.
Please allow us to override ApiClient with version without hacking jackson.
About photo - I think it's clear from screenshot.

**Describe the solution you'd like**
Make ApiClient interface, move implementation to ApiClientImpl

**Describe alternatives you've considered**

**Additional context**
![image (13)](https://user-images.githubusercontent.com/9980866/78549123-871c3400-780a-11ea-9786-b37349f9d2ad.png)

**Comment by SidneyAllen** [comment]
@mykolap thank you for the feedback.

We have some developer partners who run on Java 7 for this reason, we are using threetenbp. Threeteenbp is imported in other classes other than ApiClient, so I don't think your suggestion of 
"Make ApiClient interface, move implementation to ApiClientImpl".  But happy to see how you might accomplish this override the ApiClient while still maintaining compatibility with Java 7

We use the image as part of our unit tests to test uploading attachments. If I move it out of the repo, than anyone wishing to build and run unit tests on their own fork would not have the necessary image file.  I'm sorry you find it bother some, but I don't believe it's hampering your use of the SDK.  If you have an a way to remove the image and still build/test I'd be happy to review a PR.

I'll be closing this issue, since we wont' be actioning them - but reply to this thread if you intend on making any PRs around these two suggestions.
