### ISSUE TITLE
Maven URL does not work

### ISSUE THREAD

**Issue by rlittin** [XeroAPI/Xero-Java#36]
Hi,

We get a 404 when trying to access https://raw.githubusercontent.com/XeroAPI/Xero-Java/mvn-repo/ as described in the README.md file.

Thanks,
Richard

**Comment by SidneyAllen** [comment]
Hi @rlittin - when adding the Repository information in your POM.xml file the URL works fine.  It may not accessible via a browser. 

If you wish to browse the maven repo -it's in a branch.  https://github.com/XeroAPI/Xero-Java/tree/mvn-repo/com/xero/xero-java-sdk

**Comment by rlittin** [comment]
Hi,

Thanks, we have got it to work now.

Richard

**Comment by Raffaele838** [comment]
hi using 
compile group: 'com.xero', name: 'xero.java.sdk', version: '1.3.2' 

repositories {
	maven {
		//url "https://raw.github.com/XeroAPI/XeroAPI-Schemas/mvn-repo/"
		url "https://raw.github.com/XeroAPI/Xero-Java/mvn-repo/"
	}
}

in Gradle I receive the following error deploying the application

Could not resolve all dependencies for configuration ':modules:infomentum-oauth:compileClasspath'.
> Could not find com.xero:xero.java.sdk:1.3.2.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.pom
      https://repo1.maven.org/maven2/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.jar
      https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.pom
      https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.jar
      https://raw.github.com/XeroAPI/Xero-Java/mvn-repo/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.pom
      https://raw.github.com/XeroAPI/Xero-Java/mvn-repo/com/xero/xero.java.sdk/1.3.2/xero.java.sdk-1.3.2.jar
  Required by:
      IntranetInfomentum.modules:infomentum-oauth:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED


Could you tell me where I can find a Gradle configuration?
I need to use Gradle because all the project is based on Gradle.

Thanks.
