### ISSUE TITLE
How to build this project ?

### ISSUE THREAD

**Issue by satishetc4288** [XeroAPI/Xero-Java#6]

**Comment by mariodavid** [comment]
Hi,

i've basically the same question. Since the README.md says: 'This is the official Java SDK for the Xero API' i would assume i can get include it as a maven dependency. 

As is seems that it is not publicly available via maven central, i installed it locally (mvn install). The resulting artefact is called Xero-Java-Example, which states the fact that there is also example code included. Is there any way to just get the sdk as a dependency for my own project?

Also, the resulting artefact type is "war" instead of "jar". Is there any reason behind it?

Bye,
Mario

**Comment by SidneyAllen** [comment]
Hi @mariodavid and @satishetc4288 

Yep, we haven't gotten around to hosting this so it can be included as a maven dependency, but will in the future.  

In the meantime, go ahead and add com.xero.api and com.xero.model to your java/src directory and update your pom.xml with the dependencies and if required the plug-ins.  I'm testing this on Heroku, so I've got their plugins set for that.

I'll leave this issue open until this is resolved..

**Comment by SidneyAllen** [comment]
Hi @mariodavid and @satishetc4288 

You can now add Xero Java SDK to your project via maven dependency - it's documented in the README.   We've also created a video walking through how to setup your project in Eclipse. https://youtu.be/19UBlTDLxVc
